#server:
#  port: 9001
#
#spring:
#  application:
#    name: cloud-alibaba-provider-payment
#  profiles:
#    active: dev
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#
#management:
#    web:
#      exposure:
#        include: "*"
