server:
  port: 7002
spring:
  application:
    name: eureka-server-7002
eureka:
  instance:
    hostname: eureka7002.com
  client:
    #是否注册自己
    register-with-eureka: false
    #false代表自己就是注册中心
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
