server:
  port: 83

spring:
  application:
    name: cloud-alibaba-consumer-nacos-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

serviceUrl:
  paymentProvider: http://cloud-alibaba-provider-payment
